.TH "powerspy.X/types.h" 3 "Tue May 24 2016" "Version 1.0" "PowerSpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
powerspy.X/types.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBbyte\fP"
.br
.ti -1c
.RI "typedef signed char \fBint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef signed short long \fBint24_t\fP"
.br
.ti -1c
.RI "typedef unsigned short long \fBuint24_t\fP"
.br
.ti -1c
.RI "typedef signed long \fBint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBuint32_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File: \fBtypes\&.h\fP Author: Manuel Fedranko Version: 1\&.0 Comments: Revision history: 
.SH "Author"
.PP 
Generated automatically by Doxygen for PowerSpy from the source code\&.
